project:
  type: website

website:
  title: "livemol-docs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - href: https://github.com/zachcp/livemol
        text: GitHub
        icon: github

format:
  html:
    grid:
      sidebar-width: "150px"
      margin-width: "150px"
      body-width: "1200px"
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
